require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '243977675335',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'off',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'off',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEQvcFE1dWY4aGc5cTV2NHRyamwwdjdNUTQ0d1BZVVN2WXZBUC9PMm1XST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid2tVNEhCNkgvTzlLaUpDeVFRK1E5TzRpMXNIQ2crY1hMMzF1YlFvUDdDbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzTGluQXdjTW5qanFjZ0RWTGlzUHo2aGJ0YXpWaWllT1VmU2JBODRDeG1JPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBOHY0aWRXcDcvWjhqVWxyV1JqdThmWUVLeEhaQWxsWjFTVit1L1BxdDJrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFEMmFSa2hEY2FyUVF4VTRGNWRhQ3lydTBRbmZuRmdId0RzZGwvUG5mMjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImM4aXdKWXVSR3IrendHT1NieEF1aGllc2NqQjhmWHBTdWhoUlBlbXVYdzg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOE43QzBRcXRDYzRVQXIzcE9qL1NtZE5WQnZEZndyQmZJWGtJQjNWcHQzdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWWVjVHc5ZURMSHdhK1YyVGNiUHdJVjZjNml6aHg4dG5VQjBmK3VzWXJpVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklRUTNOdlVsWXhmOFpKV2NhU3pYTHhXcjBValFhSGNaOGYyUmJDYlpmQllZMUpnNmw1aiswK0hFUzJxOW04cFNUN1dqQ0xKYXFSNVIvMjhVYWVMM2lRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjcsImFkdlNlY3JldEtleSI6Ikk1Q3VUSndDNllvTzc5Q3A2bFp1dDZQaWx3T0JVT3BGeHp5TGw0QnYzZDA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjQzOTc3Njc1MzM1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkIyQUI5MTM2NDFEQTg1NzNFOUI0MzQ2QzdDNzBFOUNDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTgzMTAwNzZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI0Mzk3NzY3NTMzNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIwNTc2RTk3NjdCNzk0NTQzOTQxRTQ1NDIxNTI4MzVGMSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU4MzEwMDc2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNDM5Nzc2NzUzMzVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNjEzRjAyRjQ2MUQ0MTgxRjAwREMwQkNDQkE4QkMwOEEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1ODMxMDA5NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjQzOTc3Njc1MzM1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjQ5RTlCNjZDN0JFOTg3QjM4NjgxNDI0M0IzNDZFODVGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTgzMTAwOTZ9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkJUMU42WEg1IiwibWUiOnsiaWQiOiIyNDM5Nzc2NzUzMzU6MTNAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI0MzE1NjQ1MjIwMDY2MjoxM0BsaWQiLCJuYW1lIjoiTG9zdG8gUGF1bCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS2JXeDdFQkVLcmR0c1lHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUklMbG5ISFQvSWRxcDFtd1FWTm9SWVgxelp6Sk1MSW8zODdZNUJRMjlDMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoieHc2TzRBd3VONTBGeVVZdXpCK1c5SkRHMzdqaGdPblh2TlUwQlVpRkJCWWZJcVVqNWljM3NFdnZjbVRONFRiOCtOc2IwM3llT1F4QTR3bEk2TW9VRHc9PSIsImRldmljZVNpZ25hdHVyZSI6IlRYTUhkSWxPVDhWbUNaVXlFZmlMUGlHQVVNaW9POVlHSzQ5VGo1enJXS0hSdlFnYkhYWC9yU2VjV0UxbWtjZEsrT0pMSE1mWHFuSnlOYzJXN2sxUWh3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjQzOTc3Njc1MzM1OjEzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVTQzVaeHgwL3lIYXFkWnNFRlRhRVdGOWMyY3lUQ3lLTi9PMk9RVU52UXQifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1ODMxMDA3MywibGFzdFByb3BIYXNoIjoiMlAxWWhmIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFDN2IifQ==',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.43156452200662, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
